name: Build new release

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install github3.py

      - name: Run building script
        run: python tools/release-builder/main.py -t "${{ secrets.GITHUB_TOKEN }}" -repo "${{ github.repository}}" -ref "${{ github.ref }}" -log "INFO"
